# travis Need sudo permissions to execute docker 
sudo : required

# we need to first install the docker cli. We instruct travis that we want the travis cli.
services :
  - docker

# we determine the before steps that we need to build a docker file on. 
# First we need to build our docker image.

before_install :
# THe result of docker build gives us an id. We need to then use this id to start our container with that image.
# we dont have a way to read the console and get the id. 
# In this case we tag out docker command. So its easy for referenec.
  - docker build -t vijayjs2208/react-docker -f dockerfile.dev .

# TO run scripts inside the docker container.
script:
  - docker run vijayjs2208/react-docker npm run test -- --coverage

# To deploy our applciation to the aws contianer
deploy :
# there are many cloud services we can use here Ex digital ocean, Aws, Heroku. etc.
  provider : elasticbeanstalk
# region specifies the area given for our elastic bean stalk instance.  
  region : "us-east-2"
# Provide the name of the app, that we used when creating a docker contianer.  
  app :  "react-and-docker"
  env : "ReactAndDocker-env"
# this is like a s3 bucket. Its like a hard drive for storing the files.  
  bucket_name : "elasticbeanstalk-us-east-2-842816718202"
  bucket_path : "react-and-docker"
  on :
    branch : master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : 
    secure : "$AWS_SECRET_KEY"  


